### ISSUE TITLE
Browse button fails to bring up file selection on OS X 10.15 Catalina  

### ISSUE THREAD

**Issue by gitHendrix** [jchambers/pushy-console#24]
After tapping the `Browse` button for `Credentials` I get the following error in the console.

`+[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'com.apple.view-bridge': Connection interrupted`

This could be an issue with the beta of OS X 10.15. 
With some Internet searching I found: https://bugs.openjdk.java.net/browse/JDK-8227836

**Comment by jchambers** [comment]
Thanks for the heads-up. Sounds like there isn't much for us to do on our end, though, and the best course of action is to keep an eye on the upstream issue.

**Comment by jchambers** [comment]
With apologies for the long delay, this seems fine to me under macOS 10.15 and with the latest JavaFX 14 changes.
